### ISSUE TITLE
install on joomla 3.9.14 fails

### ISSUE THREAD

**Issue by web54** [tbela99/css#1]
when installing on j3.9.14 I get the error : 
Alerte
JInstaller: :Install: le fichier n'existe pas /home/weblor/public_html/web5433/tmp/install_5e1c1595796ad/gzip-master/Docs/
Plug-in Installer : impossible de copier les fichiers depuis la source

**Comment by tbela99** [comment]
You reported the issue in the wrong project. The right place is [here](https://github.com/tbela99/gzip/issues) https://github.com/tbela99/gzip/issues. Anyway I am fixing this immediately.

Thank you
