### ISSUE TITLE
Quotes and extra character

### ISSUE THREAD

**Issue by Cruglk** [tbela99/css#40]
@tbela99, Thanks for the previous fixes! And sorry, but I am writing again with found problems.

2 problems.

Code:

	$test = '#test .test2{}#test3 .test4{color:scroll;}';

Result:

	#test .test2 {
	
	}
	}#test3 .test4 {
	 color: scroll
	}

An extra character "}" appears after an empty style (no space).

Quotes again (any param in tag):

	$test = 'div[data-elem-id="1587819236980"]{background:red;}';

Result:

	div[data-elem-id=1587819236980] {
	 background: red
	}

Correct:

	div[data-elem-id="1587819236980"]{
	background:red;
	}

HTML for test:

	<div data-elem-id="1587819236980">
		test
	</div>
![1](https://user-images.githubusercontent.com/18282051/91653251-9fd20280-eaa7-11ea-8e31-283439dde6a9.png)
![2](https://user-images.githubusercontent.com/18282051/91653250-9f396c00-eaa7-11ea-8601-9ad03cc39619.png)

**Comment by tbela99** [comment]
all issues are fixed

thanks
